name: Trivy Security Scan

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker build -f deployment/docker/Dockerfile.api -t freehekim-rag-api:scan .
      - uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'freehekim-rag-api:scan'
          format: 'table'
          exit-code: '0'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

