route:
  group_by: [alertname]
  group_wait: 30s
  group_interval: 2m
  repeat_interval: 3h
  receiver: default

receivers:
  - name: default
    # Example webhook (replace with your integration)
    # webhook_configs:
    #   - url: 'http://localhost:8085/alert'

inhibit_rules:
  - source_matchers: [severity = 'critical']
    target_matchers: [severity = 'warning']
    equal: ['alertname']
