---
# FreeHekim RAG API - Ansible Inventory

all:
  children:
    production:
      hosts:
        freehekim-rag-prod:
          ansible_host: YOUR_SERVER_IP
          ansible_user: freehekim
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    staging:
      hosts:
        freehekim-rag-staging:
          ansible_host: STAGING_SERVER_IP
          ansible_user: freehekim
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    ansible_python_interpreter: /usr/bin/python3
