name: deploy-prod
on:
  workflow_dispatch:
  push:
    tags: [ 'v*.*.*' ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HC_SSH_HOST }}
          username: ${{ secrets.HC_SSH_USER }}
          key: ${{ secrets.HC_SSH_KEY }}
          script: |
            # Login to GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # Navigate to deployment directory
            cd ~/freehekim-rag-api || exit 1

            # Pull latest image
            docker compose -f docker/docker-compose.server.yml pull

            # Restart services with zero-downtime strategy
            docker compose -f docker/docker-compose.server.yml up -d --remove-orphans --no-recreate

            # Wait for service to be ready
            sleep 10

            # Health check (critical - fail deployment if unhealthy)
            curl -fsS http://127.0.0.1:8080/health || (echo "Production health check failed" && exit 1)

            # Readiness check
            curl -fsS http://127.0.0.1:8080/ready || echo "Warning: Readiness check failed (Qdrant may not be accessible)"

            # Log successful deployment
            echo "Production deployment completed successfully at $(date)"
