name: deploy-staging
on:
  push:
    branches: [dev]

env:
  IMAGE: ghcr.io/${{ github.repository }}:dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: ${{ env.IMAGE }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HC_SSH_HOST }}
          username: ${{ secrets.HC_SSH_USER }}
          key: ${{ secrets.HC_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            cd ~/hakancloud && docker compose -f docker/docker-compose.server.yml pull && docker compose -f docker/docker-compose.server.yml up -d
            curl -fsS http://127.0.0.1:8080/health || (echo "Health check failed" && exit 1)
