name: Deploy (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Sanity cleanup (legacy wiki dir)
        run: |
          rm -rf .wiki-publish || true

      - name: Docker Info
        run: |
          docker version || true
          docker compose version || true
          id || true
          groups || true
          docker ps || true

      - name: Ensure local API image tag exists
        run: |
          set -e
          IMAGE_LOCAL="docker-api:latest"
          IMAGE_TARGET="ghcr.io/freehekimteam/freehekim-rag-api:dev"
          if ! docker image inspect "$IMAGE_TARGET" >/dev/null 2>&1; then
            if docker image inspect "$IMAGE_LOCAL" >/dev/null 2>&1; then
              echo "Tagging $IMAGE_LOCAL -> $IMAGE_TARGET"
              docker tag "$IMAGE_LOCAL" "$IMAGE_TARGET"
            else
              echo "Local image $IMAGE_LOCAL not found; relying on registry pull (may fail if private)"
            fi
          fi

      - name: Docker Compose Up
        run: |
          set -x
          # Pull images if registry is accessible; ignore failures for local-only use
          docker compose -f deployment/docker/docker-compose.server.yml pull || true
          docker compose -f deployment/docker/docker-compose.server.yml up -d
