name: Deploy (manual)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      - name: Sanity cleanup (legacy wiki dir)
        run: |
          rm -rf .wiki-publish || true

      - name: Docker Info
        run: |
          docker version || true
          docker compose version || true
          id || true
          groups || true
          docker ps || true

      - name: Docker Compose Up
        run: |
          set -x
          # Pull images if registry is accessible; ignore failures for local-only use
          docker compose -f deployment/docker/docker-compose.server.yml pull || true
          docker compose -f deployment/docker/docker-compose.server.yml up -d
