name: sbom
on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with:
          path: .
          artifact-name: sbom-spdx.json
